GEMEscolar/Controllers/AlunosController.cs
using GEMEscolar.Core.Models;
using GEMEscolar.Infra.Enumerators;
using GEMEscolar.Infra.Interface;
using GEMEscolar.Infra.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GEMEscolar.Controllers
{
    public class AlunosController : Controller
    {
        private readonly IAlunosService _alunosService;
        public AlunosController(IAlunosService alunosService)
        {   
            _alunosService = alunosService;

        }
        public async Task<ActionResult> Index(CriarAlunoResponsavelModelo novoAluno)
        {
            if(string.IsNullOrEmpty(novoAluno.DocumentoResponsavel))
                return View(novoAluno);

            var response = _alunosService.CarregarResponsavelExistente(novoAluno.DocumentoResponsavel);
            return View(response);
        } 
        [HttpPost]
        public async Task<ActionResult> CriarAluno(CriarAlunoResponsavelModelo novoAlunoEResponsavel)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", novoAlunoEResponsavel);
            }

            var response = await _alunosService.CriarAluno(novoAlunoEResponsavel);
            if (!response.Success)
            {
                ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Danger, response.Message);
                return View("Index", novoAlunoEResponsavel);
            }

            ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Success, response.Message);
            return RedirectToAction("Index", "Home");
        }
    }
}

GEMEscolar/Controllers/HomeController.cs
using GEMEscolar.Core.Controllers;
using GEMEscolar.Infra.Interface;
using GEMEscolar.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace GEMEscolar.Controllers
{
    public class HomeController : MainControllerApi
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeService _homeService;

        public HomeController(ILogger<HomeController> logger, IHomeService homeService)
        {
            _homeService = homeService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var informacoesParaPainel = await _homeService.CarregarInformacoesDePainel();
            return View(informacoesParaPainel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GEMEscolar/Controllers/PagamentoController.cs
using GEMEscolar.Core.Controllers;
using GEMEscolar.Core.Entities;
using GEMEscolar.Infra.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace GEMEscolar.Controllers
{
    public class PagamentoController : MainControllerApi
    {
        public IPagamentoService _pagamentoService;
        public PagamentoController(IPagamentoService pagamentoService)
        {
            _pagamentoService = pagamentoService;
        }

        public async Task<IActionResult> Index(Guid alunoId)
        {
            return View();
        }
        public async Task<IActionResult> PagamentoAluno(Guid alunoId)
        {
            var userLogado = HttpContext.Session.GetObjectFromJson<Users>("UserLogado");

            return View("Index");
        }

    }
}

GEMEscolar/Controllers/ProfessoresController.cs
using GEMEscolar.Core.Entities;
using GEMEscolar.Infra.Enumerators;
using GEMEscolar.Infra.Interface;
using GEMEscolar.Infra.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GEMEscolar.Controllers
{
    public class ProfessoresController : Controller
    {
        private readonly IProfessoresService _professoresService;
        public ProfessoresController(IProfessoresService professoresService)
        {
            _professoresService = professoresService;
        }

        public async Task<IActionResult> Index(Professores? professores)
        {
            if(professores == null)
            {
                return View();
            }
            return View(professores);
        }
        [HttpPost]
        public IActionResult CriarNovoProfessor(Professores professor)
        {
            var professorCriado = _professoresService.CriarNovoProfessor(professor);

            if (!professorCriado)
            {
                ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Danger, "Professor já existe.");
                return View("Index", professor);
            }
            
            ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Success, "Professor criado com sucesso.");
            return View("Index", new Professores());
        }
    }
}

GEMEscolar/Controllers/TurmasController.cs
using GEMEscolar.Core.Entities;
using GEMEscolar.Infra.Enumerators;
using GEMEscolar.Infra.Interface;
using GEMEscolar.Infra.Models;
using GEMEscolar.Infra.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GEMEscolar.Controllers
{
    public class TurmasController : Controller
    {
        public ITurmasService _turmasService;
        public TurmasController(ITurmasService turmasService)
        {
            _turmasService = turmasService;
        }

        public async Task<IActionResult> Index()
        {
            var painelTurmas = await _turmasService.GetTodasTurmasComProfessor();
            return View(painelTurmas);
        }
        [HttpPost]
        public async Task<IActionResult> CriarNovaTurma(PainelTurmasModel turma)
        {
            if(turma.NovaTurma.ProfessorId == System.Guid.Empty)
            {
                ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Danger, "E necessário informar qual professor.");
                return View("Index", new PainelTurmasModel());
            }

            _turmasService.CriarNovaTurma(turma.NovaTurma);

            ViewBag.Alert = AlertService.ShowAlert(AlertsTypes.Success, "Turma criada com sucesso.");
            return RedirectToAction("Index", "Home");
        }

    }
}

GEMEscolar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
@model GEMEscolar.Core.Models.InformacoesDePainelModelo;

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
    <link href="~/css/LayoutIndex.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<div class="row">  
    <div class="col-md-12">  
        <div class="form-group">  
            @Html.Raw(@ViewBag.Alert)  
        </div>  
    </div>  
</div>
<section class="vh-50">
    <div class="container-fluid">
            <div class="card" style="border-radius: 1rem;">

                            <div class="text-center d-flex justify-content-center">
                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <span class="h1 fw-bold mb-0">Painel de controle</span>
                                </div>
                            </div>

                            <div class="row justify-content-center">
                                <a asp-controller="Alunos" asp-action="Index" type="button" class="btn btn-outline-dark m-2">Novo Aluno</a>
                                <a asp-controller="Professores" asp-action="Index" type="button" class="btn btn-outline-dark m-2">Novo Professor</a>
                                <a asp-controller="Turmas" asp-action="Index" type="button" class="btn btn-outline-dark m-2">Painel de Turmas</a>
                                <button type="button" class="btn btn-outline-dark m-2" disabled>Novo Responsável</button>
                                <a asp-controller="Pagamento" asp-action="Index" type="button" class="btn btn-outline-dark m-2">Registrar pagamento</a>
                            </div>
                            <br />

                        <form>

                            <div class="row justify-content-center">
                                <div class="card col-sm-8" style="border-radius: 1rem">
                                    <h5 class="text-center fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Alunos inadimplentes</h5>
                                    <table class="table table-bordered">
                                        <thead class="table-danger">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Aluno</th>
                                            <th scope="col">Responsável</th>
                                            <th scope="col">Qnt</th>
                                            <th scope="col">Valor Total</th>
                                            <th scope="col">Telefone</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                if(Model is not null)
                                                {
                                                    var length = 4;
                                                    var count = 1;
                                                    foreach(var item in Model.Inadiplentes)
                                                    {
                                                        if(count <= length)
                                                        {
                                                            <tr>
                                                                <th scope="row">@count</th>
                                                                <td>@item.NomeAluno</td>
                                                                <td>@item.NomeResponsavel</td>
                                                                <td>@item.QntidadeDeparcelas</td>
                                                                <td>@item.ValorTotal</td>
                                                                <td>@item.Telefone</td>
                                                            </tr>
                                                            count++;
                                                        }
                                                        else
                                                        {
                                                            break;
                                                        }
                                                    }
                                                }
                                            }
                                        
                                        </tbody>
                                    </table>
                                </div> 
                            </div>
                        </form>

                            <br />
                            <div class="row justify-content-center">
                                <div class="card col-sm-8" style="border-radius: 1rem">
                                    <h5 class="text-center fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Alunos criados recentemente</h5>
                                    <table class="table table-bordered">
                                        <thead class="table-success">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Aluno</th>
                                            <th scope="col">Responsável</th>
                                            <th scope="col">Data do Registro</th>
                                            <th scope="col">Mensalidade</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                if(Model is not null)
                                                {
                                                    var length = 3;
                                                    var count = 1;
                                                    foreach(var item in Model.AlunoCriadoRecenteModels)
                                                    {
                                                        if(count <= length)
                                                        {
                                                            <tr>
                                                                <th scope="row">@count</th>
                                                                <td>@item.Alunos.NomeAluno</td>
                                                                <td>@item.Responsavel.Nome</td>
                                                                <td>@item.Alunos.CriadoEm</td>
                                                                <td>@item.Alunos.MensalidadeValor</td>
                                                            </tr>
                                                            count++;
                                                        }
                                                        else
                                                        {
                                                            break;
                                                        }
                                                    }
                                                }
                                            }
                                        
                                        </tbody>
                                    </table>
                                </div> 
                            </div>
                            <br />
                        </div>
                    </>
                </div>
            </div>
        </div>
    </div>
</section>